# Generated by Django 4.2.10 on 2024-05-22 16:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('landline_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.ImageField(upload_to='profiles/')),
                ('city', models.CharField(choices=[('Tehran', 'تهران'), ('Mashhad', 'مشهد'), ('Isfahan', 'اصفهان'), ('Karaj', 'کرج'), ('Shiraz', 'شیراز'), ('Tabriz', 'تبریز'), ('Qom', 'قم'), ('Ahvaz', 'اهواز'), ('Kermanshah', 'کرمانشاه'), ('Urmia', 'ارومیه'), ('Rasht', 'رشت'), ('Zahedan', 'زاهدان'), ('Hamadan', 'همدان'), ('Kerman', 'کرمان'), ('Yazd', 'یزد'), ('Arak', 'اراک'), ('Ardabil', 'اردبیل'), ('Bandar Abbas', 'بندرعباس'), ('Sanandaj', 'سنندج'), ('Qazvin', 'قزوین'), ('Zanjan', 'زنجان'), ('Khorramabad', 'خرم\u200cآباد'), ('Eslamshahr', 'اسلامشهر'), ('Dezful', 'دزفول'), ('Najafabad', 'نجف\u200cآباد'), ('Sabzevar', 'سبزوار'), ('Neyshabur', 'نیشابور'), ('Saveh', 'ساوه'), ('Bushehr', 'بوشهر'), ('Quchan', 'قوچان'), ('Bojnurd', 'بجنورد'), ('Birjand', 'بیرجند'), ('Torbat-e Heydarieh', 'تربت حیدریه'), ('Sari', 'ساری'), ('Gorgan', 'گرگان'), ('Bandar-e Anzali', 'بندر انزلی')], max_length=32)),
                ('is_staff', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=32)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('plate_number', models.CharField(max_length=8, unique=True)),
                ('car_model', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('owner_first_name', models.CharField(max_length=32)),
                ('owner_last_name', models.CharField(max_length=32)),
                ('owner_phone_number', models.CharField(max_length=11, unique=True)),
                ('address', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
