
import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";
import AdminNav from "@/components/AdminNav";


export const metadata: Metadata = {
  title: "Ustat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fa" dir="rtl">

      <body>
        <AdminNav />
        <Nav />

        {children}
      </body>
    </html>
  );
}
