import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";
import AdminNav from "@/components/AdminNav";
import Errorcheck from "@/components/Errorcheck";

export const metadata: Metadata = {
  title: "Ustat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Errorcheck>
          <AdminNav />
          <Nav />
          {children}
        </Errorcheck>
      </body>
    </html>
  );
}
