// app/layout.tsx or _app.tsx
import type { Metadata } from 'next';
import './globals.css';
import Nav from '@/components/Nav';
import AdminNav from '@/components/AdminNav';
import ErrorBoundary from '@/components/ErrorBoundary'; // Correct import
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Ustat',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ErrorBoundary>
          <AdminNav />
          <Nav />
          {children}
          <Footer />
        </ErrorBoundary>
      </body>
    </html>
  );
}
