# Generated by Django 4.2.10 on 2024-05-22 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricreceipt',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver'),
        ),
        migrations.AddField(
            model_name='fabricreceipt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.orderitem'),
        ),
    ]
