# Generated by Django 4.2.10 on 2024-05-24 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requested_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 18, 11, 11, 5, 194289, tzinfo=datetime.timezone.utc)),
        ),
    ]
