# Generated by Django 4.2.10 on 2024-07-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'مبل'), ('b', 'سرویس خواب'), ('m', 'میز و صندلی'), ('j', 'جلومبلی و عسلی'), ('c', 'آینه کنسول')], max_length=16)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('dimensions', models.JSONField()),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('order_number', models.CharField(blank=True, max_length=17, unique=True)),
                ('status', models.CharField(choices=[('p', 'در انتظار تایید'), ('d', 'تایید نشده'), ('a', 'تایید شده'), ('c', 'لغو شده')], default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('p', 'در انتظار پرداخت'), ('c', 'لغو شده'), ('d', 'پرداخت شده')], default='p', max_length=1)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='sales.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'مبل'), ('b', 'سرویس خواب'), ('m', 'میز و صندلی'), ('j', 'جلومبلی و عسلی'), ('c', 'آینه کنسول')], max_length=1)),
                ('name', models.CharField(max_length=32)),
                ('dimensions', models.JSONField()),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
            ],
        ),
    ]
