# Generated by Django 4.2.10 on 2024-05-24 16:51

from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'مبل'), ('b', 'سرویس خواب'), ('m', 'میز و صندلی'), ('j', 'جلومبلی و عسلی'), ('c', 'آینه کنسول')], max_length=16)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('dimensions', models.JSONField()),
                ('images', models.JSONField()),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FabricReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('size', models.FloatField()),
                ('unit', models.FloatField()),
                ('total_size', models.FloatField()),
                ('fabric_image', image_optimizer.fields.OptimizedImageField(upload_to='fabrics/')),
                ('price', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('requested_date', models.DateField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('order_number', models.CharField(blank=True, max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'مبل'), ('b', 'سرویس خواب'), ('m', 'میز و صندلی'), ('j', 'جلومبلی و عسلی'), ('c', 'آینه کنسول')], max_length=1)),
                ('name', models.CharField(max_length=32)),
                ('dimensions', models.JSONField()),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
            ],
        ),
    ]
