# Generated by Django 4.2.10 on 2024-08-06 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'مبل'), ('b', 'سرویس خواب'), ('m', 'میز و صندلی'), ('j', 'جلومبلی و عسلی'), ('c', 'آینه کنسول')], max_length=1)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('dimensions', models.JSONField()),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
                ('fabric', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('wood_color', models.CharField(max_length=32)),
                ('show_in_first_page', models.BooleanField(default=False)),
                ('thumbnail', image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='display_items/thumbnails/')),
                ('slider1', image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='display_items/sliders/')),
                ('slider2', image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='display_items/sliders/')),
                ('slider3', image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='display_items/sliders/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('order_number', models.CharField(blank=True, max_length=17, unique=True)),
                ('status', models.CharField(choices=[('p', 'در انتظار تایید'), ('ps', 'در انتظار ثبت'), ('d', 'تایید نشده'), ('a', 'تایید شده'), ('de', 'تحویل داده شده'), ('c', 'لغو شده')], default='ps', max_length=2)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('p', 'در انتظار پرداخت'), ('c', 'لغو شده'), ('d', 'پرداخت شده')], default='p', max_length=1)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True)),
                ('transacion_number', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='sales.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'مبل'), ('b', 'سرویس خواب'), ('m', 'میز و صندلی'), ('j', 'جلومبلی و عسلی'), ('c', 'آینه کنسول')], max_length=1)),
                ('name', models.CharField(max_length=32)),
                ('dimensions', models.JSONField()),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('fabric', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('wood_color', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('thumbnail', image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='display_items/thumbnails/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
            ],
        ),
    ]
