# Generated by Django 4.2.10 on 2024-07-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayitem',
            name='type',
            field=models.CharField(choices=[('s', 'مبل'), ('b', 'سرویس خواب'), ('m', 'میز و صندلی'), ('j', 'جلومبلی و عسلی'), ('c', 'آینه کنسول')], max_length=1),
        ),
    ]
