# Generated by Django 4.2.10 on 2024-07-19 04:10

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_displayitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayitem',
            name='slider1',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='display_items/sliders/'),
        ),
        migrations.AddField(
            model_name='displayitem',
            name='slider2',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='display_items/sliders/'),
        ),
        migrations.AddField(
            model_name='displayitem',
            name='slider3',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='display_items/sliders/'),
        ),
        migrations.AddField(
            model_name='displayitem',
            name='thumbnail',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='display_items/thumbnails/'),
        ),
    ]
