# Generated by Django 4.2.10 on 2024-08-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_ordertransaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='is_for_business',
            field=models.BooleanField(default=False),
        ),
    ]
