# Generated by Django 4.2.10 on 2024-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
