# Generated by Django 4.2.10 on 2024-07-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_displayitem_slider1_displayitem_slider2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'در انتظار تایید'), ('ps', 'در انتظار ثبت'), ('d', 'تایید نشده'), ('a', 'تایید شده'), ('c', 'لغو شده')], default='ps', max_length=2),
        ),
    ]
