# Generated by Django 4.2.10 on 2024-08-21 07:44

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_ordertransaction_is_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='transacion_number',
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='proof',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='proofs'),
        ),
    ]
