# Generated by Django 4.2.10 on 2024-08-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_ordertransaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ps', 'در انتظار ثبت'), ('p', 'در انتظار تایید'), ('a', 'تایید شده'), ('pp', 'در انتظار پرداخت'), ('pd', 'پرداخت شده'), ('pse', 'در انتظار ارسال'), ('s', 'ارسال شده'), ('de', 'تحویل داده شده'), ('d', 'تایید نشده'), ('c', 'لغو شده')], default='ps', max_length=3),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='status',
            field=models.CharField(choices=[('a', 'تایید شده'), ('d', 'تایید نشده'), ('p', 'در انتظار پرداخت'), ('c', 'لغو شده'), ('d', 'پرداخت شده')], default='p', max_length=1),
        ),
    ]
