# Generated by Django 4.2.10 on 2024-08-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_ordertransaction_description_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='status',
            field=models.CharField(choices=[('a', 'تایید شده'), ('d', 'تایید نشده'), ('p', 'در انتظار پرداخت'), ('c', 'لغو شده'), ('pd', 'پرداخت شده')], default='p', max_length=2),
        ),
    ]
