# Generated by Django 4.2.10 on 2024-08-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_ordertransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayitem',
            name='type',
            field=models.CharField(choices=[('s', 'مبل'), ('b', 'سرویس خواب'), ('m', 'میز و صندلی'), ('j', 'جلومبلی و عسلی'), ('c', 'آینه کنسول و میز تلوزیون')], max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='type',
            field=models.CharField(choices=[('s', 'مبل'), ('b', 'سرویس خواب'), ('m', 'میز و صندلی'), ('j', 'جلومبلی و عسلی'), ('c', 'آینه کنسول و میز تلوزیون')], max_length=1),
        ),
    ]
